### ISSUE TITLE
[BUG] No longer builds under home-manager. 

### ISSUE THREAD

**Issue by YaroKasear** [nix-community/nixvim#1112]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

I have just pulled an update on my flake and it fails to build with the following error.

```
error:
       … while checking flake output 'nixosConfigurations'

         at «none»:0: (source not available)

       … while checking the NixOS configuration 'nixosConfigurations.loki'

         at /nix/store/94gag39fil45c81x34rragrb3radkhyh-source/lib/mkFlake.nix:132:7:

          131|     {
          132|       ${host.output}.${reverseDomainName} = host.builder ({
             |       ^
          133|         inherit (host) system;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Alias nvim-base16 is still in vim-plugins
```

I don't have any plugins enabled at all. 

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
}
```

**Comment by futu2** [comment]
same issue.
nix build logs here:
```nix
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nixvim'
         whose name attribute is located at /nix/store/bg5fbkfa5x53clcjf4p5p92k1l3w8x38-source/pkgs/stdenv/generic/make-derivation.nix:353:7

       … while evaluating attribute 'paths' of derivation 'nixvim'

         at /nix/store/jgjfwypmm1fm5jq002s5fsmmijic8rak-source/wrappers/standalone.nix:44:5:

           43|     name = "nixvim";
           44|     paths =
             |     ^
           45|       [

       … while evaluating derivation 'nixvim-configuration-reference-manpage'
         whose name attribute is located at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/stdenv/generic/make-derivation.nix:353:7

       … while evaluating attribute 'buildCommand' of derivation 'nixvim-configuration-reference-manpage'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/build-support/trivial-builders/default.nix:98:16:

           97|         enableParallelBuilding = true;
           98|         inherit buildCommand name;
             |                ^
           99|         passAsFile = [ "buildCommand" ]

       … while evaluating derivation 'options.json'
         whose name attribute is located at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/stdenv/generic/make-derivation.nix:353:7

       … while evaluating attribute 'options' of derivation 'options.json'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/nixos/lib/make-options-doc/default.nix:125:7:

          124|       ];
          125|       options = builtins.toFile "options.json"
             |       ^
          126|         (builtins.unsafeDiscardStringContext (builtins.toJSON optionsNix));

       … while evaluating the default value of option `colorschemes.base16.package`

       … from call site

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/lib/options.nix:346:15:

          345|             builtins.addErrorContext "while evaluating the ${if opt?defaultText then "defaultText" else "default value"} of option `${name}`" (
          346|               renderOptionValue (opt.defaultText or opt.default)
             |               ^
          347|             );

       … while calling 'renderOptionValue'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/lib/options.nix:383:23:

          382|   */
          383|   renderOptionValue = v:
             |                       ^
          384|     if v ? _type && v ? text then v

       … while calling anonymous lambda

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:28:22:

           27|   mapAliases = aliases:
           28|     lib.mapAttrs (n: alias: removeDistribute
             |                      ^
           29|                              (removeRecurseForDerivations

       … from call site

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:28:29:

           27|   mapAliases = aliases:
           28|     lib.mapAttrs (n: alias: removeDistribute
             |                             ^
           29|                              (removeRecurseForDerivations

       … while calling 'removeDistribute'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:16:22:

           15|   # sets from building on Hydra.
           16|   removeDistribute = alias: with lib;
             |                      ^
           17|     if isDerivation alias then

       … from call site

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:17:8:

           16|   removeDistribute = alias: with lib;
           17|     if isDerivation alias then
             |        ^
           18|       dontDistribute alias

       … while calling 'isDerivation'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/lib/attrsets.nix:780:5:

          779|     # Value to check.
          780|     value: value.type or null == "derivation";
             |     ^
          781|

       … from call site

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:29:31:

           28|     lib.mapAttrs (n: alias: removeDistribute
           29|                              (removeRecurseForDerivations
             |                               ^
           30|                               (checkInPkgs n alias)))

       … while calling 'removeRecurseForDerivations'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:9:33:

            8|   # set to appear while listing all the packages available.
            9|   removeRecurseForDerivations = alias: with lib;
             |                                 ^
           10|     if alias.recurseForDerivations or false then

       … from call site

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:30:32:

           29|                              (removeRecurseForDerivations
           30|                               (checkInPkgs n alias)))
             |                                ^
           31|                      aliases;

       … while calling 'checkInPkgs'

         at /nix/store/ia17ralvrrby1gasamzh04vivv05qrp3-nixpkgs-nixvim-doc/pkgs/applications/editors/vim/plugins/aliases.nix:23:20:

           22|   # all-packages.nix.
           23|   checkInPkgs = n: alias: if builtins.hasAttr n prev
             |                    ^
           24|                           then throw "Alias ${n} is still in vim-plugins"
```

**Comment by GaetanLepage** [comment]
Thanks for reporting.
Fixed by  https://github.com/NixOS/nixpkgs/pull/289539.

In the meantime, do not update `nixpkgs`.
The hash `a4d4fe8c5002202493e87ec8dbc91335ff55552c` is the last working `nixos-unstable` revision.

**Comment by LovingMelody** [comment]
Looks like this is still broken on NixOS-unstable-small even with the changes (commit `9f95b9c7b21a35cddfe66e92b82c7d5d6ea965de`)

**Comment by xqtc161** [comment]
Any update on this?

**Comment by mirkolenz** [comment]
The PR has been merged, we now have to wait for the channels to progress: https://nixpk.gs/pr-tracker.html?pr=289539

**Comment by GaetanLepage** [comment]
We have temporarily switched to `nixpkgs-unstable` (from `nixos-unstable`) and renamed the base16 plugin.
So you now have the choice to switch your flake to `nixpkgs-unstable` on your flake.

We will go back to `nixos-unstable` once it will include the upstream fix.

**Comment by GaetanLepage** [comment]
Everything should now be working. -> You can update your flake / use `nixos-unstable` again.
We will soon [switch back to the `nixos-unstable` channel](https://github.com/nix-community/nixvim/pull/1136) for the nixvim flake.

Sorry for this bug that was introduced upstream... by me :/

**Comment by mirkolenz** [comment]
Can confirm that it works for me. Thanks for the fast response to this bug!
