### ISSUE TITLE
[BUG] rnix-lsp has been removed as it is unmaintained

### ISSUE THREAD

**Issue by ylbeethoven** [nix-community/nixvim#1244]
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `unstable` | 
| Home Manager | `24.05-pre` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

neovim failed to build because of error. 
> error: 'rnix-lsp' has been removed as it is unmaintained

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    enable = true;
}
```

```bash
evaluating derivation 'git+file:///Users/<USER>/.dotfiles/nix#homeConfigurations."<USER>@mpro16-arm64-darwin".acti
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/x98lg26x69x9pim74hb10y5x1cqm3706-source/pkgs/stdenv/generic/make-derivation.nix:354:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/x98lg26x69x9pim74hb10y5x1cqm3706-source/pkgs/build-support/trivial-builders/default.nix:98:16:

           97|         enableParallelBuilding = true;
           98|         inherit buildCommand name;
             |                ^
           99|         passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'rnix-lsp' has been removed as it is unmaintained
```

**Comment by GaetanLepage** [comment]
Please, update your flake inputs.
We have disabled `rnix-lsp` on our side as well.
Everything should be working fine now.

**Comment by GaetanLepage** [comment]
> I've just updated my flake inputs (nixpkgs hash a35c3d443236cf60f41afd2c60ab3b684fc5feb7), and attempted to rebuild, and the issue persists.

This is weird as I have no issue on my side (and neither on the CI).

> Additionally, I see no new commits on this repo. Maybe your changes are still going through CI?

The commit that disabled `rnix-lsp` is [this one](https://github.com/nix-community/nixvim/commit/3fe9eb485cb2f3f95d9acc6ff6c50d7f581e196e).

**Comment by GoodGuyPat** [comment]
Interesting. I just tested on a different machine (also using nixpkgs unstable and home-manager unstable), and the issue still persists.

home-manager on 017b12de5b899ef9b64e2c035ce257bfe95b8ae2
nixpkgs on a35c3d443236cf60f41afd2c60ab3b684fc5feb7
nixvim on 8b500ef1db8c65ebb94b31434146e00efe4e8b9f

Does this match your setup?

**Comment by traxys** [comment]
> > I've just updated my flake inputs (nixpkgs hash a35c3d443236cf60f41afd2c60ab3b684fc5feb7), and attempted to rebuild, and the issue persists.
> 
> This is weird as I have no issue on my side (and neither on the CI).
> 
> > Additionally, I see no new commits on this repo. Maybe your changes are still going through CI?
> 
> The commit that disabled `rnix-lsp` is [this one](https://github.com/nix-community/nixvim/commit/3fe9eb485cb2f3f95d9acc6ff6c50d7f581e196e).

That only disables in our tests though

**Comment by GoodGuyPat** [comment]
You're right @traxys . I deleted the dependencies locally and the build succeeds. Just submitted a PR, let's see if we are lucky!
