### ISSUE TITLE
[BUG] `lsp-format` should get enabled if enabling `enableLspFormat`

### ISSUE THREAD

**Issue by niksingh710** [nix-community/nixvim#1690]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none-ls`  | 
| Nixpkgs      | `unstable` | 
```nix
{
  plugins.none-ls = {
    enable = true;
    enableLspFormat = true;
  };
}
```
![image](https://github.com/nix-community/nixvim/assets/60490474/13d08d19-32b7-4c04-8db1-c63697dce872)

according to the docs it should enable `lsp-format` plugin by self.

**Comment by niksingh710** [comment]
could be purely unrelated and require a new issue.
![image](https://github.com/nix-community/nixvim/assets/60490474/a5136b0e-75b1-4478-992f-2c3074bec810)

```nix
{
  plugins.none-ls = {
    enable = true;
    enableLspFormat = true;
  };
  plugins.lsp-format.enable = true;
}```

**Comment by GaetanLepage** [comment]
> could be purely unrelated and require a new issue.

This has been fixed. Please run `nix flake update`.

**Comment by niksingh710** [comment]
next time will keep in mind to do flake update before an issue. XD
was fiddling with this a long time seeing no reason for the issue to pop up 🤣

**Comment by niksingh710** [comment]
nop, reopening coz the main issue is not yet resolved.
i had added `plugins.lsp-format.enable = true;`. The build went success i closed the issue XD

**Comment by MattSturgeon** [comment]
@niksingh710 did you get this error in your build?

```
Nixvim: You have enabled the `lsp-format` integration with none-ls.
However, you have not enabled the `lsp-format` plugin itself (`plugins.lsp-format.enable = true`).
```

While the description looks to be inaccurate, the error is currently "intended" behaviour.

> Which of the two possible legit behaviors would you choose

I don't feel strongly either way, setting sane defaults is nice, but generally we avoid too much "hidden magic" :thinking: 

I believe _most_ similar options use a warning/assertion like this one?

**Comment by niksingh710** [comment]
@MattSturgeon yep, I got that error to be exact.

What I expect is that the docs should not say `Automatically enable the lsp-format` that is kindda misleading causing this error.

if the docs mention that to have this feature you need to enable `lsp-format` manually it will be better. 

moreover imo it is giving correct warning so just updatation of docs would be nice. The deep thought is that it will break the backward compatibility (consider adding this in breaking changes on the repo).

**Comment by niksingh710** [comment]
> Looks like none-ls is due an upgrade to use mkNeovimPlugin anyway, so I'll tackle this as part of that.

mkNeovimPlugin as in replacement of `pkgs.vimUtils.buildVimPlugins`?

**Comment by MattSturgeon** [comment]
> > Looks like none-ls is due an upgrade to use mkNeovimPlugin anyway, so I'll tackle this as part of that.
> 
> mkNeovimPlugin as in replacement of `pkgs.vimUtils.buildVimPlugins`?

No, it's just an internal nixvim helper we use to standardize how we build plugin-related modules.

Essentially any plugin module with a `settings` option is using that helper, ensuring we comply with [RFC42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) (allowing any options to be defined, even ones we don't know about).

You can look at our [template](https://github.com/nix-community/nixvim/blob/main/plugins/TEMPLATE.nix) or read [this section](https://github.com/nix-community/nixvim/blob/main/CONTRIBUTING.md#plugin-configurations) of our contributing guide if you're curious.

Or [search the codebase for mkNeovimPlugin](https://github.com/search?q=repo%3Anix-community%2Fnixvim%20mkNeovimPlugin&type=code) to see other examples.

**Comment by MattSturgeon** [comment]
So, all this option does is add `require('lsp-format').on_attach()` to none-ls's `on_attach` function...

This has two technical problems:
- it relies on `on_attach` not being defined
- it relies on `lsp-format` being enabled separately 

These are currently handled with a warning and assertion respectively.

---

We _could_ work around this by providing a `plugins.none-ls.onAttach` option similar to `plugins.lsp.onAttach`; that option takes a function _body_ and uses a mergable strings type (joined as lines). `settings.on_attach` could then be `visible = false`?

Unfortunately that option name is already used by the current pre-rfc42 implementation...

---

As for the second limitation, I think this is ok, because `enableLspFormat` defaults to `plugins.lsp-format.enable`'s value.

It's only really an option so that it can be marked `false` explicitly. The assertion handles explicit `true` cases.

---

With all that in mind, I'm wondering if the option should just be removed when refactoring none-ls?

If we keep it, I think the description should be documented something like:
```nix
description = ''
  Assigns lsp-format's `on_attach` callback to `plugins.none.ls.settings.on_attach` .

  - `false` - explicitly disabled
  - `true` - explicitly enabled (likely to error)
  - default - enabled when lsp-format is
'';
defaultText = literalExpression "plugins.lsp-format.enable";
example = false;
```

---

@niksingh710 @GaetanLepage @traxys:
Any thoughts on the above would be appreciated!

**Comment by niksingh710** [comment]
imo cross merging two separate plugins together may cause issue in the future.

I mean, like user's can set up `lsp-format` separately if they want and none-ls already formats the file using `vim.lsp.buf.format()`.
I guess keeping them independent of each other will be the best bet.

And yes as you mentioned for `none-ls.enableLspFormat` should take default value of `plugins.lsp-format.enable` else a force `false` or `null` and `true` should return an error.
