### ISSUE TITLE
pngpaste not available on PATH

### ISSUE THREAD

**Issue by niksingh710** [nix-community/nixvim#3467]
```nix
extraPlugins = with pkgs.vimPlugins; [ img-clip-nvim ];
extraPackages = with pkgs; if isDarwin then [ pngpaste ] else [ wl-clipboard ];
```

Have added above snippet to get dependency of `img-clip` in nvim environment, but doing `:checkhealth img-clip` reporting that `pngpaste` is not available.

In the repl I am able to see the package `pngpaste` in the `extraPackages` List.

`:checkhealth img-clip`
```log

==============================================================================
img-clip:                                                                 1 ❌

img-clip.nvim ~
- ❌ ERROR `pngpaste` is not installed

```

**Comment by MattSturgeon** [comment]
`extraPackages` works by adding its packages to neovim's PATH variable. More specifically, the `bin` directory from each package is prefixed to the PATH.

Does the `img-clip` plugin expect to find the exe another way? Or does pngpaste not expose its exe in a `bin` directory?

What does `:!which pngpaste` show in neovim? This should tell you if `pngpaste` can be found on the PATH while in neovim.

Have you called `setup` for img-clip anywhere in your lua code? Simply adding the plugin to `extraPlugins` will not cause nixvim to add any "setup" lines to your `init.lua`, unlike nixvim's `plugins.*.enable` options.

See [upstream](https://github.com/HakonHarnes/img-clip.nvim/) for available options, although they state that an empty options is usually enough:

```lua
require('img-clip').setup({})
```

**Comment by semi710** [comment]
> Does the img-clip plugin expect to find the exe another way? Or does pngpaste not expose its exe in a bin directory?

No, cause if i do `nix shell nixpkgs#pngpaste` and then run nvim, `img-clip` picks up `pngpaste`.

> What does :!which pngpaste show in neovim? This should tell you if pngpaste can be found on the PATH while in neovim.

<img width="435" alt="Image" src="https://github.com/user-attachments/assets/85df5434-73b3-472b-a3e7-0bdb7889053e" />

> Have you called setup

`setup` call was not required for the plugin.
still for ensurity i have added the setup call in `extraConfigLua` still the issue is same.

**Comment by MattSturgeon** [comment]
I can't debug this easily because I don't have access to a darwin system:

```
nix-repl> cfg = nixvimConfigurations.x86_64-linux.default.extendModules { modules = [ ({ pkgs, ... }: { extraPackages = [ pkgs.pngpaste ]; }) ]; }

nix-repl> pkg = cfg.config.build.package

nix-repl> :b pkg
       error: Package ‘pngpaste-0.2.3’ in /nix/store/q312398fgfyrm0pfzv45klxvfhj75cpm-source/pkgs/by-name/pn/pngpaste/package.nix:26 is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-unknown-linux-gnu"
         package.meta.platforms = [
           "x86_64-darwin"
           "aarch64-darwin"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.
```

But what _should_ happen is every package in `extraPackages` is added to the neovim wrapper: https://github.com/nix-community/nixvim/blob/18d838e88945b554d059db5f1fff1daed4b7bf8f/modules/top-level/output.nix#L241-L243

---

Sorry to ask a stupid question, but are you definitely running the right nvim, i.e. the one built by the nixvim config you're trying to test?

**Comment by semi710** [comment]
<img width="1005" alt="Image" src="https://github.com/user-attachments/assets/4316f241-0e40-40b9-a213-9992a89df516" />

So I was unable to find where `extendModules` come from. but attaching my package debug from repl.

> Sorry to ask a stupid question, but are you definitely running the right nvim, i.e. the one built by the nixvim config you're trying to test?

This is not a stuipid question but a genuine one, but i can ensure you have been running the correct nvim binary after doing the `nix build .#core` then `./result/bin/nvim` have also executed the build binary from the repl and nix store path.

below is the output of `!echo $PATH | tr ":" "\n"`
```log

/nix/store/8ysd9h749cj574i5ingp4wxsa9jr7715-svelte-language-server-0.17.15/bin
/nix/store/a5zb5x10908d8v91yw1a8xvidxndf0vm-ruff-0.11.13/bin
/nix/store/mxkg78zd4j8ds2mfj56dccx66nif1wag-pyright-1.1.399/bin
/nix/store/5xjhkqq4dni4h1aw8ljdk9qigq33hdcl-nixd-2.6.4/bin
/nix/store/hniglnpc8w85f8d20qr57n3r7gwra8m5-lua-language-server-3.14.0/bin
/nix/store/d01l66xi2qkp3p62khhpy7c1spqaq5gs-vscode-langservers-extracted-4.10.0/bin
/nix/store/v9f83bwbik2v4jxlgch0hj3ihd15sv7s-haskell-language-server-2.10.0.0/bin
/nix/store/hwnpyr1kgixpgaby55zybhaidxigh2ba-harper-0.41.0/bin
/nix/store/x034vzabgf523dcfqc6qyiipai8i1av2-emmet-ls-0.4.1/bin
/nix/store/nvq8rqd3fb2wn3zrpcf1a3l3r7jqnkw8-biome-1.9.4/bin
/nix/store/fnc8la64xr7d33mcqab2142y969xsnds-bash-language-server-5.4.0/bin
/nix/store/j9l00pb7vjqichx1pb9wh44mmpmsy5i8-curl-8.13.0-bin/bin
/nix/store/pnppg88x29b2rmmz54zj9rvm6rgbwml5-gcc-wrapper-14.2.1.20250322/bin
/nix/store/9pa6rygnkrdp03j4ba0w6yb5qid5x3qb-git-2.49.0/bin
/nix/store/mw69k6ynypwlwj55hq92swckwldx6m9f-glow-2.1.1/bin
/nix/store/g5bv4gi6p7ryhs2hbaryxs6ivsxa6lqc-nodejs-22.14.0/bin
/nix/store/7sm130rzasd97g50bclmbdvn0s6fdprs-ripgrep-14.1.1/bin
/nix/store/0zmp07jpxvkq7nmva5l032x58y8zxjy6-rust-analyzer-2025-06-02/bin
/nix/store/yjsgvx95rxs8z7kq8k64ihrjjcwhxxgv-pandoc-cli-3.6/bin
/nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/nix/store/0nrplqmv9zwfwinz02238m6ahp48a8m8-pre-commit-4.2.0/bin
/nix/store/r1630if1xipdb4bzyibs8pb6g134laz5-nixfmt-unstable-2025-04-04/bin
/nix/store/cvhbqa01i5yy7xmmpqp1hbnvq7kpvgsx-clang-wrapper-19.1.7/bin
/nix/store/5hgabdyqh22l57cb3qgx10lcc40d5n9p-clang-19.1.7/bin
/nix/store/d72z8b7fvvcin2p84x7h5s0abkggplzc-coreutils-9.7/bin
/nix/store/k8q0n8py04l07glgsfmvqqyqazxf04mb-cctools-binutils-darwin-wrapper-1010.6/bin
/nix/store/idmz24ps83r9mz2hkxdqwv6y4v2v7x28-cctools-binutils-darwin-1010.6/bin
/nix/store/9y6b0s0z24zvc9mh4khzvk2f83n1ywjw-xcbuild-0.1.1-unstable-2019-11-20-xcrun/bin
/nix/store/fhza62gkyw0mp1h2zls6pl1832zjjf26-libiconv-109/bin
/nix/store/9gfvy5dd2kp4xf7m3k5gm79dx1mja2lj-findutils-4.10.0/bin
/nix/store/wkgmvs8kl4a0xkr1a1cs9m3hkn07zh5f-diffutils-3.12/bin
/nix/store/3p81h24g11jfcdd7ifql71lr5mjag102-gnused-4.9/bin
/nix/store/6rdq4hg48bmqy7d8da38niai5ngg1x1s-gnugrep-3.11/bin
/nix/store/ip1m0zq8r95z6wbhk6l0k32anw8h4kc7-gawk-5.3.2/bin
/nix/store/0pfs35y6gzcd3bxiybl7vih5yfyv8bcl-gnutar-1.35/bin
/nix/store/29p1y63i1dxqspyrfima6s5ay6525zlf-gzip-1.14/bin
/nix/store/7dvq6aba13kqkvj7ay850s4q806p33vw-bzip2-1.0.8-bin/bin
/nix/store/wkq7f52a2xq4n24f545wy2fidm4z14f2-gnumake-4.4.1/bin
/nix/store/8ivrpmp3arvxbr6imdwm2d28q9cjsqvi-bash-5.2p37/bin
/nix/store/n1i5qvy1jcblq3s1ilnmc83yqcl0l8vk-patch-2.7.6/bin
/nix/store/rmn4csq2fk0scys2d0v6hgkd3yv5fkxj-xz-5.8.1-bin/bin
/nix/store/bpibjj5f5z5p73afivj0ljzbpdgnjbi0-file-5.46/bin
/Users/nikhil.singh/work/nvix/.direnv/bin
/Users/nikhil.singh/.nix-profile/bin
/etc/profiles/per-user/nikhil.singh/bin
/run/current-system/sw/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/nikhil.singh/.config/zsh/plugins/vi-mode
/Users/nikhil.singh/.config/zsh/plugins/zsh-fzf-tab
/nix/store/vmj1v3qalbp5rv927j5wfcld7arlw1zb-neovim-ruby-env/bin
```

In the above output, we can see `/nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin` is available still `img-paste` not able to find the binary.
but if the package is in my nix shell and then i run nvim it is able to find pngpaste from shell env.

**Comment by semi710** [comment]
have create a plugin req https://github.com/nix-community/nixvim/issues/3469

but still this needs to be investigated why nvim is not having the package.

**Comment by MattSturgeon** [comment]
> In the above output, we can see `/nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin` is available still `img-paste` not able to find the binary.

This is very strange!

Does listing the directory reveal any answers? 

```
ls -la /nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin
```

**Comment by semi710** [comment]
okay so this is odd, pngpaste is installed at the path but with file as named `bin`.

```
$ ls -la /nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin
Permissions Size User Group  Date Modified Name
.r-xr-xr-x   52k root nixbld  1 Jan  1970   /nix/store/h8zyr5k8aja324rdxpds18q2ga7pn3qp-pngpaste-0.2.3/bin*
```


so let's trace it
if i do `nix build nixpkgs#pngpaste` then i get result dir with a bin dir containing `pngpaste` binary with name `pngpaste`.

<img width="312" alt="Image" src="https://github.com/user-attachments/assets/ab482f74-c033-4eea-a122-9b86bc0c6aab" />

but if check the path that nixvim has for the `pngpaste` package then there is no bin dir but a bin file that is `pngpaste` binary.

**Comment by MattSturgeon** [comment]
Do you have any of nixivm's `performance` options enabled? They shouldn't touch `extraPackages`, but worth checking.

This could also be an issue that is different from one nixpkgs revision to another. Nixvim usually builds with its own pinned nixpkgs, unless you set something like `useGlobalPackages` or use a flake `follows`; neither of which are recommended.

However, if the `nixpkgs` on your flake registry (used when running e.g. `nix shell nixpkgs`), then that may be installing a different revision of the package to the one nixvim is getting from _its_ nixpkgs.

You should be able to see in your `flake.lock` what nixpkgs revision nixvim is using; under the `nixvim` node there should be an `"inputs"` object, which will reference another node like `nixpkgs_2`, looking at whatever node is referenced will tell you which revision is locked.

**Comment by semi710** [comment]
@MattSturgeon yes it does seem like nixvim's nixpkgs revision.

coz when i did
```
:u inputs.nixpkgs.legacyPackages.aarch64-darwin.pngpaste
```
the package was not avaialble in the generated shell.

where as in 
```
:u (import <nixpkgs> {}).pngpaste 
```
the pngpaste package was there.


flake.lock entry
```
"nixpkgs_2": {
      "locked": {
        "lastModified": 1749523198,
        "narHash": "sha256-How2kQw0psKmCdXgojc95Sf3K5maHB3qfINxTZFCAPM=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "cdc68935eba9f86d155585fdf6f17af6824f38ac",
        "type": "github"
      }
```

**Comment by MattSturgeon** [comment]
> yes it does seem like nixvim's nixpkgs revision.
> coz when i did [...] the package was not avaialble in the generated shell.

Interesting. That's good to know!

I guess the next question is which one is a more up-to-date revision; i.e. has something been _fixed_ in nixpkgs, or is this a _regression_ (something that has _broken_ recently).

The commit you have locked for nixvim's nixpkgs (https://github.com/nixos/nixpkgs/commit/cdc68935eba9f86d155585fdf6f17af6824f38ac) is from 4 days ago. How does that compare to the nixpkgs revision you have on your flake-registry? (Likely to be the main nixpkgs rev in your lockfile).

**Comment by semi710** [comment]
My registry flake is [latest](https://github.com/nixos/nixpkgs/tree/08fcb0dcb59df0344652b38ea6326a2d8271baff) as I have updated it while testing this issue.
and `pngtest` works as expected there.

**Comment by MattSturgeon** [comment]
In that case this sounds like a nixpkgs issue that has already been resolved. There's several ways you can workaround the issue until nixvim updates its lockfile;

- You could use multiple `pkgs` instances to get access to the newer package
- You could override nixvim's nixpkgs instance using flake `follows`
- You could use an overlay to apply whatever fixes were done in nixpkgs
- Etc

**Comment by semi710** [comment]
@MattSturgeon so I guess I got what change is causing this issue.

In unstable branch on nixpkgs `pngpaste`'s `installPhase` is:
https://github.com/NixOS/nixpkgs/blob/fd487183437963a59ba763c0cc4f27e3447dd6dd/pkgs/by-name/pn/pngpaste/package.nix#L20-L23 
this uses the install command to perform the installation.

rn i have fixed it via 
```
(pngpaste.overrideAttrs
        (_: {
          installPhase = ''
            runHook preInstall
            install -Dm555 pngpaste $out/bin/pngpaste
            runHook postInstall
          '';
        }))
```

**Comment by GaetanLepage** [comment]
We just bumped the flake.lock. There is a chance this has been fixed.

**Comment by semi710** [comment]
@GaetanLepage Just updated my flake still the same issue, The issue seems to be in line of the package.

```sh
install -Dm555 pngpaste $out/bin
```

as `nixos-25.05` branch package works fine with nixvim.

the thing is `pngpaste` works fine on system in `unstable` and `25.05` but inside nixvim's `extraPackages` the installation is fails to work with `unstable` branch.

via `extraPackages` the installation `pngpaste` binary name changes to `bin`.

nixpkgs needs a patch 
```
install -Dm555 pngpaste $out/bin/pngpaste
```

**Comment by khaneliman** [comment]
https://github.com/NixOS/nixpkgs/pull/415998 ([tracker](https://nixpk.gs/pr-tracker.html?pr=415998))

**Comment by MattSturgeon** [comment]
> My registry flake is [latest](https://github.com/nixos/nixpkgs/tree/08fcb0dcb59df0344652b38ea6326a2d8271baff) as I have updated it while testing this issue. and `pngtest` works as expected there.

Strange that it was actually a regression when it looked like something that'd been fixed.

Maybe this was a case of nixvim's lock actually being _ahead_ of your system lock, because you had latest `nixos-unstable` while we had a recent `nixpkgs-unstable`?

EDIT: yes, your system nixpkgs was https://github.com/NixOS/nixpkgs/commit/08fcb0dcb59df0344652b38ea6326a2d8271baff from the 8th of June, while nixvim's nixpkgs was https://github.com/NixOS/nixpkgs/commit/cdc68935eba9f86d155585fdf6f17af6824f38ac from the 10th of June.

So even though you had the latest `nixos-unstable` at the time, nixvim still had a newer nixpkgs because we follow `nixpkgs-unstable`.
